#index:
#    path: /
#    controller: App\Controller\DefaultController::index

logout_route:
  path: /logout

page_yoga:
  path: /yoga
  controller:    Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template:  'static/yoga.html.twig'
    maxAge:    86400
    sharedAge: 86400
  methods: GET



page_ayurveda:
  path: /ayurveda
  controller:    Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template:  'static/ayurveda.html.twig'
    maxAge:    86400
    sharedAge: 86400
  methods: GET



page_thym:
  path: /thym
  controller:    Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template:  'static/thym.html.twig'
    maxAge:    86400
    sharedAge: 86400
  methods: GET



page_naturophatie:
  path: /naturophatie
  controller:    Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template:  'static/naturophatie.html.twig'
    maxAge:    86400
    sharedAge: 86400
  methods: GET
